name: Lab 01 - Hello Actions

on: push


jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo "Hello from GitHub Actions!"
      - name: Who am I?
        run: whoami
      - name: What operating system is this?
        run: cat /etc/os-release
      - name: Where am I?
        run: pwd
      - name: Print today's date
        run: date
      - name: Check Python version
        run: python3 --version
